version: "3.8"

services:
  frontend:
    build: .
    container_name: ecommerce-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:1337"
      NEXT_PUBLIC_STRIPE_PUBLIC_KEY: "pk_test_51QmJ9fP2e90YVnJD4rFUspk6gAAQX6apTWERLoPpBYhwANzbahLD1JNF0o0eLU5DgJnj5lvVNm2CbnKF0lpU8Cst00YFrJll8w"
