import type { Metadata } from "next"
import { Montserrat } from "next/font/google"

import { AppWrapper } from "@/providers/AppWrapper"

import Footer from "./components/Footer"
import "./globals.css"

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by n0vaWeb infinity",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <AppWrapper>
          {children}
          <Footer />
        </AppWrapper>
      </body>
    </html>
  )
}
